---
title: "Homework 4"
author: "Casey Gibson"
output: html_document
---

### Problem 1

```{r}
srrs2 <- read.table("/Users/gcgibson/Downloads/marriage.csv", header=T, sep=",")
#names(srrs2)
#unique(srrs2$state) # states
# we'll use MN

n <- length(srrs2$agemarried)
y.i <- srrs2$agemarried
#x.i <- floor.i

# get county index variable
county.i <- as.vector(srrs2$ethnicgroup)
county.j <- unique(county.i)
J <- length(county.j)
countygetj.i <- rep (NA, n) 
for (j in 1:J){
  countygetj.i[county.i==county.j[j]] <- j
}

# state mean, n.j and county means
ybarbar = mean(y.i) # state mean
sample.size.j <- as.vector (table (county.i))
cty.mns.j = tapply(y.i,countygetj.i,mean) # county means

# to plot observations and county means ~ sample sizes, 
# easier to see if sample sizes are slighly jittered
set.seed(12345)
sample.size.jittered.j <- sample.size.j*exp (runif (J, -.1, .1))

```





```{r}

library(rjags)
library(R2jags)

model <- 
"model {
for (i in 1:n){
  y.i[i] ~ dnorm(alpha.j[getj.i[i]],tau.y)
}

for (j in 1:J){
 alpha.j[j] ~ dnorm(mu.alpha,tau.alpha)
}

tau.y <- pow(sigma.y, -2)
tau.alpha <-  pow(sigma.alpha, -2)

mu.alpha ~ dnorm(20,5)
sigma.y ~ dunif(0,5)
sigma.alpha ~ dunif(0,5)

}"

jags.data <- list(  y.i = y.i,  n = n, getj.i  = countygetj.i, J = J)
parnames <- c("alpha.j", "mu.alpha", "sigma.y", "sigma.alpha")
mod0 <-jags(data = jags.data, 
            parameters.to.save=parnames, 
            model.file = textConnection(model))
# point estimates of the county means
partpooled.j <- mod0$BUGSoutput$summary[paste0("alpha.j[", 1:J, "]"), c("mean")]

max(mod0$BUGSoutput$summary[, c("Rhat")])
min(mod0$BUGSoutput$summary[, c("n.eff")])
# check traceplots, at least for hyperparameters
mcmc.array <- mod0$BUGSoutput$sims.array
# plenty of built-in functions for traceplots but I like this one
# (I'll add these functions to a separate R script for use in future scripts)
#---------------
PlotTrace <- function(#Traceplot for one parameter
  ### Trace plot for one parameter and add loess smoother for each chain
  parname, mcmc.array,##<< needs to be 3-dimensional array!
  n.chains= NULL, n.sim= NULL, main = NULL){
  if (is.null(main)) main <- parname
  if (is.null(n.sim)) n.sim <- dim(mcmc.array)[1]
  if (is.null(n.chains)) n.chains <- dim(mcmc.array)[2]
  plot(c(mcmc.array[,1,parname]), type = "l", ylab = parname,  main = main,
       ylim = c(min(mcmc.array[,,parname]),max(mcmc.array[,,parname])))
  for (chain in 1:n.chains){
    lines(c(mcmc.array[,chain,parname]), type = "l", col = chain)
  }
  for (chain in 1:n.chains){
    curve(predict(loess(c(mcmc.array[,chain,parname])~seq(1,n.sim)),x), lty = 2, lwd = 3, add = TRUE, type = "l", col = chain)
  }
}
par(lwd = 3, cex.axis = 1.5, cex.lab = 1.5, cex.main = 1.5,mar = c(5,5,1,1), mfrow = c(1,3))
PlotTrace(parname = "mu.alpha", mcmc.array)
PlotTrace(parname = "sigma.alpha", mcmc.array)
PlotTrace(parname = "sigma.y", mcmc.array)

par(lwd = 3, cex.axis = 1.5, cex.lab = 1.5, cex.main = 1.5,mar = c(5,5,1,1), mfrow = c(1,3))
hist(c(mcmc.array[,,"mu.alpha"]), freq = F, main = "", xlab = expression(mu[alpha]))
curve(dnorm(x,1,3), add = T, col = 2)

hist(c(mcmc.array[,,"sigma.alpha"]), freq = F, main = "", xlab = expression(sigma[alpha]))
curve(dunif(x,0,5), add = T, col = 2)

hist(c(mcmc.array[,,"sigma.y"]), freq = F, main = "", xlab = expression(sigma[y]))
curve(dunif(x,0,5), add = T, col = 2)

```


